### PR TITLE
ci: Add release-plz CI action which will create a PR with a suggestion to cut a release on every commit to master

### PR DESCRIPTION
**Pull request by frol**

### CODE REVIEW

**Comment by MarcoIeni** [comment]
Hey, thanks for using release-plz, I'm the author.
From time to time I look at [this](https://github.com/search?type=code&q=path%3A*.yml+OR+path%3A*.yaml+MarcoIeni%2Frelease-plz-action) github search, and I saw you added release-plz to this project.
However, by looking at the logs of the `master` branch it seems release-plz is not working properly:
image
The reason for that is that release-plz thinks that the current version of the packages is 0.0.0. Let's try to fix this together, either in release-plz or in borsh-rs 😄 

First, is this notation standard in the rust?
```toml
[workspace.metadata.workspaces]
# shared version of all public crates in the workspace
version = "0.10.2"
```

Because running `cargo metadata` gives me the version 0.0.0.
image
This is what release-plz uses.

**Comment by MarcoIeni** [comment]
By using the [standard way](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) of defining a common version (https://github.com/near/borsh-rs/pull/134), release-plz works.
However, I found issue https://github.com/MarcoIeni/release-plz/issues/635.
Basically release-plz will override the shared version:
image
So I don't suggest to merge https://github.com/near/borsh-rs/pull/134 until this release-plz issue is fixed (I would try to fix it this week).

**Comment by frol** [comment]
@MarcoIeni Thanks for reaching out! I love release-plz!

The 0.0.0 versioning is a custom setup we have here (I guess, there are some historical reasons). Also, we keep changelogs at the root of the project started for all the crates - is there a way to tweak release-plz to use it instead of creating crate-local changelogs?

**Comment by MarcoIeni** [comment]
> Thanks for reaching out! I love release-plz!

Thank you! I will do my best to make it work for you! 😃 

> The 0.0.0 versioning is a custom setup we have here (I guess, there are some historical reasons).

If you merge https://github.com/near/borsh-rs/pull/134 and I implement https://github.com/MarcoIeni/release-plz/issues/635 then we should be good for this point 👍 

> Also, we keep changelogs at the root of the project started for all the crates - is there a way to tweak release-plz to use it instead of creating crate-local changelogs?

It makes sense! I created https://github.com/MarcoIeni/release-plz/issues/637.

----

These two issues are now my top priority for release-plz. I hope to get them done by this or next week. I will ping you when I'm done 👍

**Comment by MarcoIeni** [comment]
I implemented these two issues 🥳 If you want, you can give release-plz another try :)

**Pull request merged**
