### PR TITLE
feat: Optimize borsh, remove hint

### PR DESCRIPTION
**Pull request by pmnoxx**
There is no need to use `hint.rs`. Linux by default will not allocate all memory, when `Vec::with_capacity` is called.

In LInux, by default, allocated pages of size 4096. When an allocation is needed that spawns across multiple pages, by default, all pages point to a special page, with only zeroes written it. Linux using COW (Copy-on-write) technique, new pages will be physically allocated, if and only if, there is a write to a given page.

See https://en.wikipedia.org/wiki/Copy-on-write

I wrote a code, which proves it:
```rust
let _result = Vec::with_capacity(1_000_000_000_000);
```
This allocates, one Petabyte of memory, that that works!

Benefits:
- memory saving, we use exactly the amount of memory needed
- cleaner code
- safe

TODO:
- rewrite rest of the code, to be list this, if this PR gets approved

### CODE REVIEW

**Comment by matklad** [comment]
Yeah, Linux does overcommit, but this is a happy case. This code needs to be robust and handle sad cases as well.  There are several ways this can get broken. The biggest one is probably that the user can override this behavior:

```console
[matklad@Ishmael:~/tmp]$ cat main.rs
fn main() {
    let _result: Vec<u8> = Vec::with_capacity(200_000_000);
}

[matklad@Ishmael:~/tmp]$ rustc main.rs

[matklad@Ishmael:~/tmp]$ ./main

[matklad@Ishmael:~/tmp]$ ulimit -v 100000

[matklad@Ishmael:~/tmp]$ ./main
memory allocation of 200000000 bytes failed
Aborted (core dumped)
bash: xrealloc: subst.c:749: cannot allocate 128 bytes (2404352 bytes allocated)
```

The second big reason is that borsh is a library -- we don't know where it gets used. It very well might be not linux, but windows or wasm or whatever. 

There's also the thing that I *think* Rust aborts for allocations bigger that `usize::MAX/2` *in the library code*.

So, I think we should have this logic in.

**Comment by frol** [comment]
I agree with @matklad. I am not comfortable allocating some arbitrary amount of RAM ahead of time.

Does it measurably improve any of the benchmarks out there?

**Comment by pmnoxx** [comment]
> Yeah, Linux does overcommit, but this is a happy case. This code needs to be robust and handle sad cases as well. There are several ways this can get broken. The biggest one is probably that the user can override this behavior:
> 
> ```
> [matklad@Ishmael:~/tmp]$ cat main.rs
> fn main() {
>     let _result: Vec<u8> = Vec::with_capacity(200_000_000);
> }
> 
> [matklad@Ishmael:~/tmp]$ rustc main.rs
> 
> [matklad@Ishmael:~/tmp]$ ./main
> 
> [matklad@Ishmael:~/tmp]$ ulimit -v 100000
> 
> [matklad@Ishmael:~/tmp]$ ./main
> memory allocation of 200000000 bytes failed
> Aborted (core dumped)
> bash: xrealloc: subst.c:749: cannot allocate 128 bytes (2404352 bytes allocated)
> ```
> 
> The second big reason is that borsh is a library -- we don't know where it gets used. It very well might be not linux, but windows or wasm or whatever.
> 
> There's also the thing that I _think_ Rust aborts for allocations bigger that `usize::MAX/2` _in the library code_.
> 
> So, I think we should have this logic in.

@matklad @frol 
Yes, that makes sense. However, there are ways to do it safety.

We can make performance improvements, by changing api, and introducing `Context`, similar to what `deepsize` has.
It `Context`, we could store a counter, which is the count of data allocated, but not used yet. As log as it's reasonable, let's say less than 512mb, we could use the fast path, otherwise resort to the slow path.

The overhead of adding extra data structure, will be small, compared to the cost we pay currently for doing reallocations.

Btw, a feature, where you stop serializing, after some memory threshold is reached, could be useful.

> Does it measurably improve any of the benchmarks out there?

Anyway, before doing any  optimizations, I think its' good to do it by adding benchmarks first. I'll do that, before any further optimizations.

**Comment by matklad** [comment]
>As log as it's reasonable, let's say less than 512mb, we could use the fast path, otherwise resort to the slow path.

This seems mostly equivalent to what we already do with our capacity calculations, no? It's just that today we limit by 4k rather than 512mb. One tweak we can make there is to make that dependent on the remaining buffer size. That is, not `4096` but `4096.max(buf.len() * 2)` or something. 

>The overhead of adding extra data structure, will be small, compared to the cost we pay currently for doing reallocations.

did we actually measure this overhead? I would be surprised if there's a problem here, as we do allocate small capacities, and I'd expect that most borsh messages are small. 

>a feature, where you stop serializing, after some memory threshold is reached, could be useful.

That's already possible: you can create your own `Write` impl which errors after a certain amount of bytes written. See https://github.com/near/borsh-rs/issues/23#issuecomment-816633365 for something similar (computing the total length of the message).

**Pull request closed without merging**
