### PR TITLE
chore: apply Schema on field_type

### PR DESCRIPTION
**Pull request by Mehrbod2002**
Fixes : #112 
Apply schema on field_types

### CODE REVIEW

**Review by frol — APPROVED** [review]
@Mehrbod2002 Thanks for the contribution!

**Comment by frol** [comment]
@Mehrbod2002 Please, fix the snapshots for the tests, so the tests don't fail.

**Comment by Mehrbod2002** [comment]
> @Mehrbod2002 Please, fix the snapshots for the tests, so the tests don't fail.

Sure

**Comment by Mehrbod2002** [comment]
@frol you can review it now

**Comment by Mehrbod2002** [comment]
@frol 
Is there anything Bad related to this PR ?

**Comment by frol** [comment]
@Mehrbod2002 Sorry, I got distracted while waiting on CI checks. Thanks for pinging me!

**Pull request merged**
