### PR TITLE
Implemented (de)serialization for nonzero integer

### PR DESCRIPTION
**Pull request by Boiethios**

### CODE REVIEW

**Review by austinabell — APPROVED** [review]
Mutually exclusive with #35. This one is more concise and more tests, but also was opened later

**Comment by Boiethios** [comment]
Do you know when it's reviewed? I need this change, and there're very few line to review.

**Comment by matklad** [comment]
Yeah, let's merge this, the impl and tests look good to me!

**Comment by matklad** [comment]
:facepalm: travis refuses to go away, opened https://near.zulipchat.com/#narrow/stream/308449-nearinc.2Fcore-tools/topic/borsh.20repo.20admin

**Comment by Boiethios** [comment]
> facepalm travis refuses to go away, opened https://near.zulipchat.com/#narrow/stream/308449-nearinc.2Fcore-tools/topic/borsh.20repo.20admin

I hope it'll be solved soon 😛 
I think that the error message could be better, because it's a bit cryptic for now. What do you think about `"Zero value read for a NonZero integer"` or something like that?

**Comment by matklad** [comment]
>or something like that?

No strong feelings one way or another. My heuristic would be to check what `serde_json` does and copy that without much extra delibiration.

**Comment by Boiethios** [comment]
> My heuristic would be to check what `serde_json` does and copy that without much extra delibiration.

Did that, thanks! I think it's important that people understand easily what happens when reading an error message.

**Comment by Boiethios** [comment]
@frol Thanks for the merge. Is it possible to publish this change (maybe as a patch version?)

**Comment by frol** [comment]
@miraclx Are you actively working on getting the automated publishing pipeline for borsh-rs or should I publish it manually for now?

**Comment by miraclx** [comment]
Released on https://github.com/near/borsh-rs/releases/tag/v0.9.2

> #### Crate Links
> 
>  - borsh: https://crates.io/crates/borsh/0.9.2
>  - borsh-derive: https://crates.io/crates/borsh-derive/0.9.2
>  - borsh-derive-internal: https://crates.io/crates/borsh-derive-internal/0.9.2
>  - borsh-schema-derive-internal: https://crates.io/crates/borsh-schema-derive-internal/0.9.2

**Pull request merged**
